# Generated by Django 5.0.3 on 2024-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='photos', verbose_name='Изображение'),
        ),
    ]
